### ISSUE TITLE
Add templates that generate email when rejecting registrations

### ISSUE THREAD

**Issue by lakinwecker** [Lichess4545/heltour#260]
When we reject registrations, we do so for a number of different reasons:

1. Duplicate registrations.
2. Rejecting due to ineligibility to participate in the league and there is no hope of becoming eligible.
3. Rejecting due to lack of games played (provisional rating).

It would be good to record the reason why (we currently do so via comment), and additionally it would be good if we could select from a set of pre-made email templates for the second 2 options and have an email be sent to registration.

**Comment by glbert-does** [comment]
1. Duplicate registrations are not possible anymore
3. Afaik none of the leagues rejects for provisional ratings at this point (we just leave provisional registrations pending)

so that only leaves 2, and a selection of templates will not be necessary. a simple rejection email for everyone should be enough.
